# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Papas-Colors
tagline:          'johwanghee, java, javascript'
url:              http://johwanghee.github.io/papas-colors/
paginate:         1
baseurl:          /papas-colors/
author:
  name:           Jo Hwanghee
  url:            http://johwanghee.github.io
  email:          johwanghee@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/JoHwanghee/johwanghee.github.io/papas-colors
